AWSTemplateFormatVersion: 2010-09-09
Resources:
  NPCTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "Id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "Id"
          KeyType: "HASH"
      TableClass: STANDARD
Outputs:
  NPCTableName:
    Value: !Ref NPCTable
    Export:
      Name:
        'Fn::Sub': '${AWS::StackName}-NPCTableName'
  NPCTableArn:
    Value: !GetAtt NPCTable.Arn
    Export:
      Name:
        'Fn::Sub': '${AWS::StackName}-NPCTableArn'